# Travis now has haxe support, but something is going wrong. Try the old-school way
language: python

# Install Haxe before running the test.
before_script:
  - sudo apt-get update  > /dev/null                               # run update before installing anything
  - sudo apt-get install python-software-properties -y > /dev/null # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y > /dev/null      # add the ubuntu ppa that contains haxe
  - sudo apt-get update > /dev/null                                # pull info from ppa
  - sudo apt-get install haxe -y > /dev/null                       # install haxe (and neko)
  - mkdir ~/haxelib > /dev/null                                    # create a folder for installing haxelib
  - haxelib setup ~/haxelib > /dev/null
  - haxelib install buddy > /dev/null

# Run the test!
script:
  - haxe behaviour.hxml
  - neko behaviour.n